productScreen and productCard
GiliEllen/react-natve-e-commerce-frontend pull request #3
Opened 2024-03-21 19:18 UTC by liran26

finish productCard for now. added product screen & product card so i can see what i did.
beacuse i didn't getting yet a product id i used constant one.
there is no images in DB so i used two local one to test layout.

after i'll get those two from outside i'll test it again with the uncomments codes

2024-03-25 21:11 UTC, GiliEllen commented on components/ProductCard.js
> +                const productData = await getSpecificProduct("65faf26b8dec99b4cd38a768"); // This is the product ID for testing, real id will be passed from the products screen
please fix, this is meant to be generic.

2024-03-25 21:12 UTC, GiliEllen commented on components/ProductCard.js
> +                {/* {product && product.images.map((image, index) => (
remove comments

2024-03-25 21:12 UTC, GiliEllen commented on components/ProductCard.js
> +                {/* no images in DB so replaced with local for testing */}
remove comments

2024-03-25 21:12 UTC, GiliEllen commented on components/ProductCard.js
> +                            lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
what is this? remove

2024-03-25 21:13 UTC, GiliEllen requested changes
please follo the comments and fixe before updating PR

2024-03-26 16:58 UTC, liran26 commented
fixed all

2024-03-27 15:42 UTC, GiliEllen requested changes

2024-03-27 15:42 UTC, GiliEllen commented on App.js
> +        <Tab.Screen name="productCard" component={ProductScreen} />
remove

2024-03-27 15:42 UTC, GiliEllen commented on api/productsApi.js
> +    console.log(data);
remove

2024-03-27 15:42 UTC, GiliEllen commented on components/ProductCard.js
> +                    console.error("Product not found");
tell user, no item was found

2024-03-27 15:42 UTC, GiliEllen commented on components/ProductCard.js
> +                        <Text style={{ color: "#222222", fontSize: 14 }}>
create object for styling

2024-03-27 15:42 UTC, GiliEllen commented on components/ProductCard.js
> +                    <Text style={{ color: "white", textAlign: "center" }}>ADD TO CART</Text>
create object for styling

2024-03-27 15:42 UTC, GiliEllen commented on components/ProductCard.js
> +const ProductCard = ({ navigation, productId }) => {
remove navigation prop

2024-03-27 15:42 UTC, GiliEllen commented on components/ProductCard.js
> +
const navigation = useNavigation();

2024-03-27 16:40 UTC, GiliEllen approved these changes

2024-03-27 16:40 UTC, merged